# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:40
# pylint: skip-file



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0005_auto_20160224_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
    ]
