# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0007_datapoint_generator_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPointVisualizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=1024)),
                ('generator_identifier', models.CharField(db_index=True, max_length=1024)),
                ('last_updated', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
