# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 21:48
# pylint: skip-file

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0009_reportjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportjob',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='reportjob',
            name='generator_identifier',
        ),
        migrations.RemoveField(
            model_name='reportjob',
            name='last_updated',
        ),
    ]
