# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 21:58
# pylint: skip-file



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0010_auto_20160319_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='completed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
