# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 02:44
# pylint: skip-file



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0014_auto_20160812_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='identifier',
            field=models.CharField(db_index=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
