# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:00
# pylint: skip-file

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0015_datafile_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='secondary_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
