# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:38
# pylint: skip-file



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0017_datasourcealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcealert',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
