# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 19:39
# pylint: skip-file



from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0019_datasourcealert_alert_level'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='datapoint',
            index_together=set([('source', 'generator_identifier', 'created'), ('source', 'generator_identifier')]),
        ),
    ]
