# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 21:33
# pylint: skip-file

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0021_auto_20170731_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcealert',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='datasourcealert',
            name='alert_level',
            field=models.CharField(choices=[('info', 'Informative'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=64),
        ),
        migrations.AlterField(
            model_name='datasourcealert',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='datasourcealert',
            name='updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
