# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 21:50
# pylint: skip-file

from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

from ..models import install_supports_jsonfield

class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0023_auto_20170731_2137'),
    ]

    if install_supports_jsonfield():
        operations = [
            migrations.AddField(
                model_name='datasource',
                name='performance_metadata',
                field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
            ),
        ]
    else:
        operations = [
            migrations.AddField(
                model_name='datasource',
                name='performance_metadata',
                field=models.TextField(max_length=(32 * 1024 * 1024 * 1024), blank=True, null=True)
            ),
        ]
