# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 22:13
# pylint: skip-file

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0024_datasource_performance_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='performance_metadata_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
