# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 17:05
# pylint: skip-file



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0025_datasource_performance_metadata_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataServerMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('value', models.CharField(max_length=1024)),
            ],
        ),
    ]
