# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 17:08
# pylint: skip-file

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0026_dataservermetadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataServerMetadata',
            new_name='DataServerMetadatum',
        ),
    ]
