# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:39
# pylint: skip-file



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0027_auto_20170824_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataservermetadatum',
            name='value',
            field=models.TextField(max_length=1048576),
        ),
    ]
