# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 01:47
# pylint: skip-file



from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0028_auto_20170828_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataPointVisualizations',
            new_name='DataPointVisualization',
        ),
    ]
