# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0031_reportjobbatchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjobbatchrequest',
            name='started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
