# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0032_reportjobbatchrequest_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='user_agent',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
