# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 14:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0037_datasource_suppress_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='generated_at',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
