# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 14:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0038_auto_20180821_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataservermetadatum',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
