# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0040_auto_20181213_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportjob',
            name='data_end',
        ),
        migrations.RemoveField(
            model_name='reportjob',
            name='data_start',
        ),
    ]
