# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 00:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0041_auto_20181213_2231'),
        ('passive_data_kit', '0040_auto_20181202_1131'),
    ]

    operations = [
    ]
