# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0042_merge_20181213_1844'),
        ('passive_data_kit', '0040_auto_20181115_1100'),
    ]

    operations = [
    ]
