# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-10 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passive_data_kit', '0043_merge_20190105_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataServerApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=1024, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdk_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data server API token',
                'verbose_name_plural': 'data server API tokens',
            },
        ),
    ]
