# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0044_dataserverapitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='passive_data_kit.DataBundle'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='data_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='passive_data_kit.DataPoint'),
        ),
    ]
