# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0045_auto_20190326_1308'),
        ('passive_data_kit', '0045_auto_20190225_1821'),
    ]

    operations = [
    ]
