# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 16:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0057_databundle_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databundle',
            name='encrypted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
