# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0058_auto_20190609_1107'),
    ]

    operations = [
    	# Removed migrations that would convert JSON fields to text fields.
    ]
