# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0058_auto_20190609_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='configuration_json',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='datasourcealert',
            name='alert_details',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='reportdestination',
            name='parameters',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='reportjobbatchrequest',
            name='parameters',
            field=models.TextField(max_length=34359738368),
        ),
    ]
