# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 04:26


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0059_auto_20190614_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataServerAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=4096)),
                ('request_type', models.CharField(db_index=True, max_length=4096)),
                ('request_time', models.DateTimeField(db_index=True)),
                ('request_metadata', models.TextField(max_length=34359738368)),
                ('successful', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataServerAccessRequestPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=4096)),
                ('request_type', models.CharField(max_length=4096)),
                ('request_time', models.DateTimeField()),
                ('request_metadata', models.TextField(max_length=34359738368)),
                ('successful', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
