# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-06 17:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0062_auto_20190805_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databundle',
            name='compression',
            field=models.CharField(choices=[('none', 'None'), ('gzip', 'Gzip')], db_index=True, default='none', max_length=128),
        ),
    ]
