# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0064_auto_20190820_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='reference',
            field=models.URLField(blank=True, max_length=1048576, null=True),
        ),
    ]
