# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0066_auto_20190820_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='platform_version',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='model',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
