# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0068_remove_deviceissue_platform_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceissue',
            name='state',
            field=models.CharField(choices=[('opened', 'Opened'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('wont-fix', "Won't Fix")], default='opened', max_length=1024),
        ),
    ]
