# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0072_auto_20190922_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataserver',
            name='request_key',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
