# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 16:02


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

from ..models import install_supports_jsonfield

class Migration(migrations.Migration):
    dependencies = [
        ('passive_data_kit', '0073_dataserver_request_key'),
    ]

    if install_supports_jsonfield():
        operations = [
            migrations.AlterField(
                model_name='appconfiguration',
                name='configuration_json',
                field=django.contrib.postgres.fields.jsonb.JSONField(),
            ),
        ]
    else:
        operations = [
            migrations.AlterField(
                model_name='appconfiguration',
                name='configuration_json',
                field=models.TextField(max_length=34359738368),
            ),
        ]
