# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 19:48


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0077_deviceissue_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='passive_data_kit.DataSourceGroup'),
        ),
    ]
