# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 21:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0078_auto_20191126_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='databundle',
            name='errored',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
