# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0082_auto_20200324_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databundle',
            name='compression',
            field=models.CharField(choices=[('none', 'None'), ('gzip', 'Gzip')], default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='errored',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='recorded',
            field=models.DateTimeField(),
        ),
    ]
