# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-27 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0084_auto_20200327_1118'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='appconfiguration',
            index_together=set([('is_valid', 'is_enabled'), ('is_valid', 'is_enabled', 'evaluate_order')]),
        ),
    ]
