# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 02:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0085_auto_20200327_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
