# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 21:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0087_auto_20200419_1654'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='datapoint',
            index_together=set([]),
        ),
    ]
