# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 02:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0088_auto_20200419_1705'),
        ('passive_data_kit', '0086_auto_20200416_1237'),
    ]

    operations = [
    ]
