# Generated by Django 2.2.16 on 2021-01-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0091_auto_20200918_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('passive_data_kit_dashboard_access', 'Access Passive Data Kit dashboard'), ('passive_data_kit_export_access', 'Create Passive Data Kit data exports')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
