# pylint: skip-file
# Generated by Django 3.2.17 on 2023-02-28 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0093_alter_datapoint_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='passive_data_kit.datapoint'),
        ),
    ]
