# pylint: skip-file
# Generated by Django 3.2.17 on 2023-03-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0094_alter_datafile_data_point'),
        ('passive_data_kit', '0094_auto_20230221_1840'),
    ]

    operations = [
    ]
