# pylint: skip-file
# Generated by Django 3.2.19 on 2023-06-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0095_merge_20230307_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='passive_data_kit.appconfiguration'),
        ),
    ]
