# pylint: skip-file
# Generated by Django 3.2.24 on 2024-03-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0096_datasource_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfiguration',
            options={'ordering': ['name']},
        ),
    ]
