# Generated by Django 3.2.23 on 2024-01-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0096_datasource_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfiguration',
            options={'ordering': ['name']},
        ),
    ]
