# pylint: skip-file
# Generated by Django 3.2.24 on 2024-11-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0097_auto_20241030_1410'),
        ('passive_data_kit', '0098_alter_appconfiguration_configuration_json_and_more'),
    ]

    operations = [
    ]
