# pylint: skip-file
# Generated by Django 4.2.20 on 2025-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit', '0099_merge_20241120_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='configuration_json',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='properties',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='properties',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='performance_metadata',
            field=models.TextField(blank=True, max_length=34359738368, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcealert',
            name='alert_details',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='reportdestination',
            name='parameters',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='parameters',
            field=models.TextField(max_length=34359738368),
        ),
        migrations.AlterField(
            model_name='reportjobbatchrequest',
            name='parameters',
            field=models.TextField(max_length=34359738368),
        ),
    ]
