version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.8
      - image: circleci/postgres:9.6.9-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            sudo apt-get update && sudo apt-get install -y gdal-bin python3-gdal
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project passive_data_kit
            mkdir django
            cd django
            django-admin.py startproject pdk
            mv ../passive_data_kit pdk
            cd pdk
            ls
            pwd
            cp passive_data_kit/circle_settings.py pdk/settings.py
            cp passive_data_kit/circle_urls.py pdk/urls.py
            python manage.py migrate
            python manage.py test
            cp passive_data_kit/.pylintrc .
            pylint passive_data_kit
            bandit -r .      
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "/home/circleci/django/pdk/passive_data_kit/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app
