name: "Passive Data Kit"
services:
  db:
    image: postgis/postgis:13-3.4
    hostname: db
    volumes:
      - ./volumes/db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    healthcheck:
      test: "pg_isready -U ${PG_USER} -d ${PG_DB}"
      interval: 1s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: .env
    command: bash /app/run.sh
    volumes:
      - type: bind
        source: ${DJANGO_MEDIA_FILES}
        target: /media
      - type: bind
        source: ${DJANGO_STATIC_FILES}
        target: /static
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      db:
        condition: service_healthy
